### ISSUE TITLE
Problems with parameters marshalling for invoke/invokefunction/invokescript

### ISSUE THREAD

**Issue by aprasolova** [CityOfZion/neo-go#104]
I'm trying to use neo-go's functions from RPC package to send requests to my privnet rpc port. I observe a problem that parameters for smart contract don't marshal correctly. Say, I'd like to perform the request with the body like:
```
{
    "jsonrpc": "2.0",
    "id": "2",
    "method": "invoke",
    "params": [
        "0x64743d938ee52fa63eb97b101a5e203679213e3b",
        "get",
        [
            {
                "type": "Array",
                "value": [
                	{"type": "Integer", "value": "1"}
                ]
            }
        ]
    ]
}
```
and to do it programmaticaly I write the code like:

```
    intParam := []smartcontract.Parameter{
        {
            Type: smartcontract.IntegerType,
            Value: "1",}}

    pparams := []smartcontract.Parameter {
        {
            Type: smartcontract.ArrayType,
            Value: intParam, }}

    response, _ = client.InvokeFunction(scHash, "get", pparams) 

```
The issue is, when JSON marshalling runs, the constants of type `smartcontract.Parameter` are turned into the numbers, while it should be strings like `"Integer"` or `"Array"` (according the [docs](http://docs.neo.org/en-us/node/cli/2.9.2/api/invokefunction.html) at least!).

What I get instead of my expectations is
```
{
    "jsonrpc": "2.0",
    "method": "invokefunction",
    "params":
        [
            "0x64743d938ee52fa63eb97b101a5e203679213e3b",
            "get",
            [
                {
                    "type": 8,
                    "value":
                     [
                            {
                                "type": 2,
                                 "value": "1"}]}]],
    "id": 1
}
```

Am I doing something wrong or it really is a problem?
If so, I forked the repo and implemented a `MarshalJSON` function for `smartcontract.Parameter` type. I also added wrapper for `Invoke` RPC function. If you're interested you may look at it [here](https://github.com/aprasolova/neo-go/tree/feature-invoke-params).

**Comment by im-kulikov** [comment]
@aprasolova can you close issue if it resolved by https://github.com/CityOfZion/neo-go/pull/106
