### ISSUE TITLE
[Q] There is something strange with versions numbers

### ISSUE THREAD

**Issue by im-kulikov** [CityOfZion/neo-go#110]
https://github.com/CityOfZion/neo-go/blob/5b57a10250d415bda55a25ae01565bb4ace9e927/VERSION#L1

For now version is `v0.45.12`
In releases, latest is `v0.44.10`

Mb we can fix this and bump to `v0.44.11`?

- [here](https://github.com/CityOfZion/neo-go/blob/e2f42e92a094fab583173b44b47300abf1b48814/VERSION#L1) version was bumped from `0.44.11` ≈> `0.45.11`
- [and here](https://github.com/CityOfZion/neo-go/blob/5b57a10250d415bda55a25ae01565bb4ace9e927/VERSION#L1) `0.45.11` ≈> `0.45.12`

**Comment by AlexVanin** [comment]
Maybe something like version auto-increment in Makefile would be nice for version number consistency?

**Comment by im-kulikov** [comment]
@AlexVanin yeah! thx! Great idea..
Makefile command, that would fetch latest release from repo and increment current if necessary

**Comment by aprasolova** [comment]
@im-kulikov, nice idea! -- espessialy important for me now, when I'm stuck with what version should I put in my [PR](https://github.com/CityOfZion/neo-go/pull/109). @anthdm, what do you say? And what do you think on im-kulikov's proposal?

**Comment by anthdm** [comment]
I was not a big fan of the VERSION thing from the beginning. Cause each PR that will be merged into some branch does not mean we are releasing this as a new version/fix/patch. It's also super tedious to merge PR now without doing some nasty branch checkouts from the one that actually made the PR.

**Comment by anthdm** [comment]
I think we should just remove the VERSION check and make all PR's merged to a `dev` branch.

**Comment by anthdm** [comment]
@im-kulikov What do you think of merging `neo-storm` back in `neo-go`?

**Comment by im-kulikov** [comment]
@anthdm Why do we want to do this?

**Comment by im-kulikov** [comment]
Oh.. in this case it makes sense

**Comment by im-kulikov** [comment]
Another way, we can split functionality between small repos.. what you think about it?

**Comment by aprasolova** [comment]
> Another way, we can split functionality between small repos.. what you think about it?

+1, guys from neo-python follow this way, for example. Also a good example is go implementation of [libp2p](https://github.com/libp2p). Every component is a small repo.

**Comment by anthdm** [comment]
@aprasolova @im-kulikov I'm removing the `VERSION` dependency on the CI. We will figure something else out how to deal with that. It makes my life as a reviewer much simpler.

**Comment by im-kulikov** [comment]
@anthdm I can close issue or we keep it to discuss about split / merge repos?

**Comment by anthdm** [comment]
@im-kulikov You can close this one and let's open a new one for discussing the new project structure and distribution of task.

**Comment by im-kulikov** [comment]
@anthdm ok, thx
