### ISSUE TITLE
improve error message

### ISSUE THREAD

**Issue by dauTT** [CityOfZion/neo-go#140]
As requested by @kim, the error message must follow this convention:
 
`{"jsonrpc":"2.0","error":{"code":-2146233033,"message":"One of the identified items was in an invalid format."},"id":1}`

To find more about the context of this issue read [here](https://github.com/CityOfZion/neo-go/pull/135#discussion_r257521065)

**TODO**: refactor the errors methods in the  [errors.go](https://github.com/CityOfZion/neo-go/blob/master/pkg/rpc/errors.go) file accordingly and amends all tests.

**Comment by im-kulikov** [comment]
Today my PR was merged into neo-project/neo, and I can change that in our repo

**Comment by im-kulikov** [comment]
Wait until #135 will be merged
