### ISSUE TITLE
 Implemented rcp method GetAccountState #124 

### ISSUE THREAD

**Issue by hal0x2328** [CityOfZion/neo-go#153]
https://github.com/CityOfZion/neo-go/pull/124

**Comment by im-kulikov** [comment]
It’s merged, mb we can close task?

**Comment by hal0x2328** [comment]
This issue was added in the process of creating issues for payment purposes according to the new system process, although I'm going to push for just inserting the PRs directly into the master CoZ payment project for all PRs without a linked pre-existing issue, because it just doesn't seem to add much value and is a lot of work to keep manually correlating and adding these, and is just going to slow the process of payments down without adding any real value.

**Comment by im-kulikov** [comment]
thanks for explaning
