### ISSUE TITLE
Setup CI/CD

### ISSUE THREAD

**Issue by decentralisedkev** [CityOfZion/neo-go#157]
https://circleci.com/ or https://travis-ci.org/ are known solutions. However any will do.

**Comment by im-kulikov** [comment]
Resolved by #161 @decentralisedkev?

**Comment by decentralisedkev** [comment]
Not yet. Travis-CI won't show it under organisations. But CircleCI does

**Comment by im-kulikov** [comment]
@decentralisedkev should I make CircleCI?

**Comment by decentralisedkev** [comment]
Seems to be a problem with CircleCI, going to keep this open until we solve it

**Comment by im-kulikov** [comment]
Can you describe what’s the problem?

**Comment by im-kulikov** [comment]
try to run CI on this PR https://github.com/CityOfZion/neo-go/pull/170

you forgot merge with dev-branch, and CI don't know how to run without settings:

https://github.com/CityOfZion/neo-go/tree/vm

**Comment by im-kulikov** [comment]
as I can see, TravisCI works fine - https://github.com/CityOfZion/neo-go/runs/70605267
can we close issue?
