### ISSUE TITLE
VM:Implement Basic VM

### ISSUE THREAD

**Issue by decentralisedkev** [CityOfZion/neo-go#159]

**Comment by decentralisedkev** [comment]
One possible interface could be:

```
type VM interface {
   Execute(opcodes []byte) bool
}
```

returning true if Execution was successful, false otherwise

**Comment by decentralisedkev** [comment]
@im-kulikov Hey thanks for the offer! This has already been taken, I was opening this up to keep track of any ongoing conversations

**Comment by im-kulikov** [comment]
@decentralisedkev cool, can you assign he to issue?

**Comment by im-kulikov** [comment]
issue, without assign, a little confusing

**Comment by decentralisedkev** [comment]
@im-kulikov Yeah sorry for the confusion, I'm not able to assign anyone outside of CoZ github group

**Comment by im-kulikov** [comment]
sounds sad. @fabwa @anthdm  could you give rights for @decentralisedkev?
or mb @hal0x2328 can help us?

**Comment by hal0x2328** [comment]
I would but I don't have the power either

**Comment by im-kulikov** [comment]
So sad

**Comment by fabwa** [comment]
Will do

**Comment by decentralisedkev** [comment]
I have not heard back from those who were assigned this issue. I will assign this to myself to get the ball rolling.
