### ISSUE TITLE
Amend VM State after C# implementation (Master branch)

### ISSUE THREAD

**Issue by dauTT** [CityOfZion/neo-go#176]
Erik wants to remove the `FlagsAttribute` from `VMState`
https://github.com/neo-project/neo-vm/pull/84

This means that the changes in [PR-123](https://github.com/CityOfZion/neo-go/pull/123) need to be rolled back.

**Comment by decentralisedkev** [comment]
Note: This has been implemented in the BasicVM on `dev`
