### ISSUE TITLE
CLI Structure

### ISSUE THREAD

**Issue by revett** [CityOfZion/neo-go#18]
Task to setup CLI structure using [urfave/cli](https://github.com/urfave/cli) package.

**Comment by revett** [comment]
Picking this up this weekend 👍

**Comment by anthdm** [comment]
@revett I already added the dep and 2 commands for debugging contracts. The rest is up to you.

**Comment by anthdm** [comment]
### Example of current available commands
```
./bin/neo-go contract compile somecontract.go
./bin/neo-go contract opdump somecontract.go
./bin/neo-go node -tcp 4000 -rpc 5000
```

### Nice to have for operating on the blockchain
```
./bin/neo-go block 99
./bin/neo-go block 11172aed3a61fe64ae82cb02e886757d352a4452f956a0703d0809880538ba58
```

**Comment by anthdm** [comment]
CLi is kinda bootstrapped for now and will expand as the project grows. I think its best to create different issues for each CLI implementation. Therefore I will close this issue to keep things nice and clean.
