### ISSUE TITLE
Move size calculations to DEV

### ISSUE THREAD

**Issue by dauTT** [CityOfZion/neo-go#185]
Find a proper home in the DEV branch for these files (from the master branch):

> 1) serializable.go
> 2) size.go
> 3) size_test.go

@TODO: 
1) Difference analysis: ([reference](https://github.com/CityOfZion/neo-go/pull/183#discussion_r266254485))
2) Add size calculation where is applicable
3) Finalize test cases in PR #183 by uncommenting the assert statement  related to size calculation
4) Add more tests.

**Comment by decentralisedkev** [comment]
1. Could we not use the length of the byte slice?

**Comment by dauTT** [comment]
[I don't think so.](https://github.com/CityOfZion/neo-go/pull/183#discussion_r266252670)

**Comment by decentralisedkev** [comment]
Ran some tests and it seems that we can use the length of the byte slice: 

To reproduce, I took the tx from your neo-python post: https://github.com/CityOfZion/neo-python/issues/914 with the expected value of 302.

Then ran the following code in register_test:

```
func TestSizeTx(t *testing.T) {
	rawtx := "400060245b7b226c616e67223a227a682d434e222c226e616d65223a2254657374436f696e227d5dffffffffffffffff08034b44ed9c8a88fb2497b6b57206cc08edd42c5614bd1fee790e5b795dee0f4e1167f97110a66136d38badc7b9f88eab013027ce4900014423a26aeca49cdeeb9522c720e1ae3a93bbe27d53662839b16a438305c20906010001e72d286979ee6cb1b7e65dfddfb2e384100b8d148e7758de42e4168b71792c60001e1a210b00000067f97110a66136d38badc7b9f88eab013027ce490141405d8223ec807e3416a220a75ef9805dfa2e36bd4f6dcc7372373aa45f15c7fadfc96a8642e52acf56c2c66d549be4ba820484873d5cada00b9c1ce9674fbf96382321034b44ed9c8a88fb2497b6b57206cc08edd42c5614bd1fee790e5b795dee0f4e11ac"

	rawtxBytes, _ := hex.DecodeString(rawtx)

	reg := NewRegister(0)

	r := bytes.NewReader(rawtxBytes)
	err := reg.Decode(r)
	assert.Equal(t, nil, err)

	assert.Equal(t, 302, len(reg.Bytes()))
}
```

**Comment by dauTT** [comment]
In the master branch I tested this case as well and seems to work as you said: 
![image](https://user-images.githubusercontent.com/30392990/54498651-2f164500-490a-11e9-8bea-8db971b3cfa5.png)

The size caculation is applied to others struct as well so we need to do more analsys to confirm your hypothesis.

**Comment by dauTT** [comment]
@decentralisedkev ,

most of the time your approach match the standard way used by neo-python and C#. I have tested for serveral transactions and blocks and it looks ok. However there are case like this one wich do not match:
`C#/neo-python` give 219. Wheares `dev neo-go` gives 227.
```go
func TestEncodeDecodeInvoc4(t *testing.T) {
	// taken from mainnet c4bb9b638da2e5f4a88ffcc4cb1d4f6693e7f19b7f78d242068254a6c77721f9
	// https://neoscan.io/transaction/C4BB9B638DA2E5F4A88FFCC4CB1D4F6693E7F19B7F78D242068254A6C77721F9

	rawtx := "d1015904802b530b14d5a682e81b8a840cc44b3b360cbd0f1ee6f50efd14235a717ed7ed18a43de47499c3d05b8d4a4bcf3a53c1087472616e7366657267fb1c540417067c270dee32f21023aa8b9b71abcef166fc47646b02d3f92300000000000000000120235a717ed7ed18a43de47499c3d05b8d4a4bcf3a0000014140b9234cad658c4d512bca453908a0df1c2beda49c544ec735bb492b81b4d0974ac8d66046061b3d0ce823e27c71fef1ee6a8f2fa369198ac74acedd045901d7222321030ab39b99d8675cd9bd90aaec37cba964297cc817078d33e508ab11f1d245c068ac"

	rawtxBytes, _ := hex.DecodeString(rawtx)

	i := NewInvocation(30)

	r := bytes.NewReader(rawtxBytes)
	err := i.Decode(r)
	assert.Equal(t, nil, err)

	//227 dev-neo-go versus 219 neo-python/C#
	fmt.Println(i.Size())
}
```
I could break 219 as follow:


![image](https://user-images.githubusercontent.com/30392990/54790569-e1b21480-4c36-11e9-87ef-c80b08419c1b.png)

It is currently difficult to break the bytes calculation in dev neo-go. I have tried and come up with 214. @decentralisedkev / @im-kulikov, do you know how to reconcile the remaining `13 = 227-214` bytes in dev-neo-go?

**Comment by im-kulikov** [comment]
@dauTT I take a look at this weekend

**Comment by decentralisedkev** [comment]
@dauTT Do you know the circumstances for when this happens?

If you take the length of the raw hex string, it will say 454, which means that the total amount of bytes is 227. 

Regarding the breakdown, you are right, there is no easy way to break down the transaction, other than looking at the hex representation. Maybe we can file an issue for this; to have a debugging format for devs. If it is easier to work out the sizes in neo-python/C# then maybe you can check where they drop the 8 bytes from the size calculation?

**Comment by decentralisedkev** [comment]
By the way, here is a link on the difference between Parity(Rust) , Geth(Go) and EthereuJ(Java) for the eth network. https://ethereum.stackexchange.com/questions/62653/can-anyone-explain-whats-the-difference-between-mist-geth-parity-in-simple-term

Since each implementation is not a carbon copy of the other "a bug in one client will not have as drastic of an effect, as errors to the network should be ignored by the other working clients."

I believe this was the purpose for having more than one implementation, but will double check for you

**Comment by im-kulikov** [comment]
@decentralisedkev @dauTT  thanks for info

![](https://user-images.githubusercontent.com/30392990/54790569-e1b21480-4c36-11e9-87ef-c80b08419c1b.png)

As I understand next `structures` contains 1 byte (to marshal structure-type):
- Outputs
- Inputs
- Attribute
- Script
- Witness

@dauTT can you provide hex of transaction with unmarshaled info for thus "bug"?

**Comment by dauTT** [comment]
@im-kulikov,
here are more details related to the [transaction above](https://neoscan.io/transaction/C4BB9B638DA2E5F4A88FFCC4CB1D4F6693E7F19B7F78D242068254A6C77721F9). The neo-python output looks like this:

```
{'attributes': [{'data': '235a717ed7ed18a43de47499c3d05b8d4a4bcf3a',
                 'usage': 32}],
 'gas': '0',
 'net_fee': '0',
 'script': '04802b530b14d5a682e81b8a840cc44b3b360cbd0f1ee6f50efd14235a717ed7ed18a43de47499c3d05b8d4a4bcf3a53c1087472616e7366657267fb1c540417067c270dee32f21023aa8b9b71abcef166fc47646b02d3f923',
 'scripts': [{'invocation': '40b9234cad658c4d512bca453908a0df1c2beda49c544ec735bb492b81b4d0974ac8d66046061b3d0ce823e27c71fef1ee6a8f2fa369198ac74acedd045901d722',
              'verification': '21030ab39b99d8675cd9bd90aaec37cba964297cc817078d33e508ab11f1d245c068ac'}],
 'size': 219,
 'sys_fee': '0',
 'txid': '0xc4bb9b638da2e5f4a88ffcc4cb1d4f6693e7f19b7f78d242068254a6c77721f9',
 'type': 'InvocationTransaction',
 'version': 1,
 'vin': [],
 'vout': []}
```

**Comment by dauTT** [comment]
Thanks @decentralisedkev /@im-kulikov,for investigating further. I will also try to do some research this weekend. :smile:

**Comment by dauTT** [comment]
I believe I found an explanation for the missing 8 bytes:
The C#/ neo-python does not include the Gas amount in the size calculation:
```C# 
//Size invocation transaction = Size base transaction + Size Script  
public override int Size => base.Size + Script.GetVarSize();  

//Size base transaction
public virtual int Size => sizeof(TransactionType) + sizeof(byte) + Attributes.GetVarSize() + Inputs.GetVarSize() + Outputs.GetVarSize() + Witnesses.GetVarSize();
```
[Size invocation link](https://github.com/neo-project/neo/blob/master/neo/Network/P2P/Payloads/InvocationTransaction.cs#L15
)
[Size base transaction link](https://github.com/neo-project/neo/blob/master/neo/Network/P2P/Payloads/Transaction.cs#L111)

I think `Dev neo-go` does include the gas amount size:

https://github.com/CityOfZion/neo-go/blob/dev/pkg/wire/payload/transaction/invocation.go#L38

![image](https://user-images.githubusercontent.com/30392990/54849799-973ba100-4ce5-11e9-9ec9-39fd2b56dcdd.png)

Do you agree?

**Comment by decentralisedkev** [comment]
@dauTT Nice catch!

**Comment by decentralisedkev** [comment]
For invocation transactions with version > 1, there is a gas amount; https://github.com/CityOfZion/neo-python/blob/master/neo/Core/TX/InvocationTransaction.py#L59

We could minus 8 bytes from invocation transaction with version > 1,  until a PR is made to neo-python and c-sharp. WDYT? @dauTT @im-kulikov

**Comment by dauTT** [comment]
@decentralisedkev ,

I want to extend the `Transaction` interface in connection to this issue as follow:

![image](https://user-images.githubusercontent.com/30392990/54865153-8597df00-4d61-11e9-8644-52a614f65b38.png)

**Is it okay?** 

Then we can automatically generated test cases lke this one:
```go
func TestBlockDecodeEncode21(t *testing.T) {
	// block taken from mainnet: 00000b94b3ff3e62c1f17c5291779173be7197e7626ebfaa545aeea50d99e6b5

	rawBlock := "00000000cfcde828f6ae822ed04cd9888baa1e42208cab4aca68884fc98cf20bd93ec40eceb136a4a3c5604dc8ca0a57377056aefcfbe023ce6f2ef4ea0affd4837d0c82b52fed5a1c04220056e8bc285d39b0da59e75d652b5d3827bf04c165bbe9ef95cca4bf5501fd4501401a0684d652e4785804ab2dea0c0a024e0037971985bab9abfc0c72fc473d4eb839f2bb921000594cd4319c8cd4d5ee14c83fbb5d90b1928f61f2a11c1ef4a2b040bcbca8bca01d65efb989ebfc9bf733fdd377956a1eca525fa94050f9545546fd4a116b85e093f8c0d76185d6f89c7a4e0912abe6d5b16b9d4dd23289e6d8ddae40a9d327dc024131d85f1da2d6da9f0ed9018799d6db8b4389bfb077725e836c9c6828d1068183ad7da714323e845ea1cc742d334e70c46c34b8716a925f3c894a40fa1e4710b7d1ebac17fc5ca73f27d8bfee63d86640fe095bb169539ba198f850a63fe01727c5fd7d56ecabc17be5670f219c43107197c6f239f8245a895b83ca4021c1e6a104dc6a33184c52b5e26ee80ed6a937f11a72082c88a6605766a5a6d64834d69a3d337801b1a3e70cb9242f4b7307c3e37a7044610fa03a4135da567df1552102486fd15702c4490a26703112a5cc1d0923fd697a33406bd5a1c00e0013b09a7021024c7b7fb6c310fccf1ba33b082519d82964ea93868d676662d4a59ad548df0e7d2102aaec38470f6aad0042c6e877cfd8087d2676b0f516fddd362801b9bd3936399e2103b209fd4f53a7170ea4444e0cb0a6bb6a53c2bd016926989cf85f9b0fba17a70c2103b8d9d5771d8f513aa0869b9cc8d50986403b78c6da36890638c3d46a5adce04a2102ca0e27697b9c248f6f16e085fd0061e26f44da85b58ee835c110caa5ec3ba5542102df48f60e8f3e01c48ff40b9b7f1310d7a8b2a193188befe1c2e3df740e89509357ae08000056e8bc2800000000d1015904802b530b14d5a682e81b8a840cc44b3b360cbd0f1ee6f50efd14235a717ed7ed18a43de47499c3d05b8d4a4bcf3a53c1087472616e7366657267fb1c540417067c270dee32f21023aa8b9b71abcef166fc47646b02d3f92300000000000000000120235a717ed7ed18a43de47499c3d05b8d4a4bcf3a0000014140b9234cad658c4d512bca453908a0df1c2beda49c544ec735bb492b81b4d0974ac8d66046061b3d0ce823e27c71fef1ee6a8f2fa369198ac74acedd045901d7222321030ab39b99d8675cd9bd90aaec37cba964297cc817078d33e508ab11f1d245c068ac8000000186b01317d6756a8b281ea8d3854cc70e0fad0c231b595e3f2627db7be9ecc57a0000019b7cffdaa674beae0f930ebe6085af9093e5fe56b34a5c220ccdcf6efc336fc500e1f50500000000ab8d1f9b5576b5fa1ed41bb183cb237365eae91d01414053d2b2a46acd340a120a7923bf7af26865d20dedfa7fa613097416e71fc6333c5bbeca1009e94080eae3c4ec1affce515cb34acbd8c1e9eef4730faa39fb2e8223210347b5a7b5cd4768517cda87c83388ca4a40e3593bae26674d708325e848a72716acd1012000c1087769746864726177691f559d5eea8ca22910a3feb0e4637c0f2e71c50e000000000000000003a15100000000000000000000000000000000000000000000000000000000000000a39b7cffdaa674beae0f930ebe6085af9093e5fe56b34a5c220ccdcf6efc336fc5a422516f4bacac82e15853fa89fb960d9e7b8b77f400000000000000000000000001ef7ddab3cceeeecb3a8c7c9402d4aca4e5222abf09160fb1eb6371c045e6732b0000019b7cffdaa674beae0f930ebe6085af9093e5fe56b34a5c220ccdcf6efc336fc500c2eb0b0000000022516f4bacac82e15853fa89fb960d9e7b8b77f401020000000200049dbf6423d1d71c70eeccf25a8040d68a3337b818d40c38f834c01783207ec5940000d40d0d897192e9cf2c94da4ade91f5523890a0b6ef03e97ab94cb6eb3c31950600004882135fb7352844a1824a7c56bedc8558491b33e6b6eebc9dda2f238c3c6cd800000fe3ff131a819934e5b4e32a76686a14d8fe482017374ddfe370f2cc18d72e4d0000000001e72d286979ee6cb1b7e65dfddfb2e384100b8d148e7758de42e4168b71792c60361c1b030000000053a26712d0fcdb1ee0c031c76b66ecf7d4589c920141407bfc93a036b2ddbd09c52cd3838fffdee8093afdc4dbaae27e6e9401e6dbd7e36222678571d0dc74549094078775a59ef0f887f3ea949bc7fb43279b47418d1c2321036d7ffe865eb2bee12cbf8a06efdd686aeee2a54cc5e7322397ad50f64f5966c3ac800001ff076e656f2d6f6e6502f43ec07918050f398d1059deeede662f8d1f81d1dccff00eed294e0a66a77247000019a62a256b8c8d0ad707bbc13debabae3114af06383a7666b69fb30c4c20cd520000019b7cffdaa674beae0f930ebe6085af9093e5fe56b34a5c220ccdcf6efc336fc500c2eb0b0000000058042b7aad34fc952f790af13ad9529cca09010c014140d707fed016e4e7b576d434cfdfa749f19c16702898d0d677a33cdbff7582be024d72ac4be4672bdb3f3efa6c6549804084406f01fa5c8f37acaf8b7707e1258c23210278d506474eff10b1693e0124f844ce21011e9c166ced94f905e90d8bc6447e44ac80000001457eeed281e050d32cc7ea01f0b75c4c9daf01a0ccbe93aac3f5814f41eabec50000019b7cffdaa674beae0f930ebe6085af9093e5fe56b34a5c220ccdcf6efc336fc500f15365000000007cefc40518315e87ef78ec4b902194b33d37cb72014140f51cdc58fc7ed9994c70d060e612c4bac0f9d8e8b57aa2a1356e30eb9841cdd6554529c839d3711cb219547ca691e3a7031074c9a7049fe88997febb1b8a99802321028a254584df91e77a1e357cbfd219347f5f38edb3f1058b1e57bbb79db0abd2daac800001ff076e656f2d6f6e650130458594deb942e153de40875a3b48c7b679318269fb75a323caf4cec1ddd2cb0000019b7cffdaa674beae0f930ebe6085af9093e5fe56b34a5c220ccdcf6efc336fc50046c32300000000c5edd73d7904e1460b0333b7c096d7d977928ec1014140d052edcedc027a080ba43ddf3d3c1c319b5248ecfce95199dd18e78fef7cbb53fe3417d062b7364b5e18471397757a6288a297911df7107fba1de6072ca46653232102bfeb247cf9ae2817bcdeb81bfa8ac29ba5eb8a2abfb549deb7c8c9622a746238ac"
	rawBlockBytes, _ := hex.DecodeString(rawBlock)

	b := Block{}

	r := bytes.NewReader(rawBlockBytes)
	b.Decode(r)

	expected := map[string]txAttributes{ // 8 trans

		"d8d221a066013f68ae194eb50e6cf523bd7dd1113a8d0f1e92695f6387ba9e9e": txAttributes{Type: "MinerTransaction", Size: 10, Version: 0},
		"c4bb9b638da2e5f4a88ffcc4cb1d4f6693e7f19b7f78d242068254a6c77721f9": txAttributes{Type: "InvocationTransaction", Size: 227, Version: 1},
		"643be3425ac36e65cc05a661cf6d4d63cd823bbf2a72291c7c62ca57f91f28a5": txAttributes{Type: "ContractTransaction", Size: 202, Version: 0},
		"b4a18d36234fb84de6d3209d0b5c5faeb891974292a8abadfbb2cdeccba68af1": txAttributes{Type: "InvocationTransaction", Size: 244, Version: 1},
		"c19f030a9b8fdd8c1c343670a0920055bbc9f224a0205961fb0befe1c00efa08": txAttributes{Type: "ClaimTransaction", Size: 305, Version: 0},
		"b0f13f4bbd175a7aec0bf4d7837abde62cd39580b28e43e0214f0614da04afe9": txAttributes{Type: "ContractTransaction", Size: 245, Version: 0},
		"c95952d3a2b6b920c04516097d0538a01bf93c416bebbfb6546f4ec78ce4a97c": txAttributes{Type: "ContractTransaction", Size: 202, Version: 0},
		"b17098c5a177f5c9ee6f9c1103eac470e17224280f2704dcbd74bf4a4fe83a2a": txAttributes{Type: "ContractTransaction", Size: 211, Version: 0},
	}

	for _, tx := range b.Txs {

		txID, _ := tx.ID()
		if attrs, ok := expected[txID.ReverseString()]; ok {
			t.Logf("problem with TransactionID: %s", txID)
			assert.Equal(t, attrs.Size, tx.Size())
			assert.Equal(t, attrs.Type, tx.TypeTx().String())
			assert.Equal(t, attrs.Version, int(tx.VersionTx()))

		} else {
			t.Fatalf("invalid TransactionID: %s", txID)
		}

	}

	assert.Equal(t, len(expected), len(b.Txs))

	// Block specifc tests
	assert.Equal(t, 0, int(b.Version))
	assert.Equal(t, "0ec43ed90bf28cc94f8868ca4aab8c20421eaa8b88d94cd02e82aef628e8cdcf", b.PrevHash.ReverseString())
	assert.Equal(t, "820c7d83d4ff0aeaf42e6fce23e0fbfcae567037570acac84d60c5a3a436b1ce", b.MerkleRoot.ReverseString())
	assert.Equal(t, 1525493685, int(b.Timestamp))
	assert.Equal(t, 2229276, int(b.Index))

	nextConsensus, err := address.FromUint160(b.NextConsensus)
	assert.Equal(t, nil, err)
	assert.Equal(t, "APyEx5f4Zm4oCHwFWiSTaph1fPBxZacYVR", nextConsensus)

	assert.Equal(t, "401a0684d652e4785804ab2dea0c0a024e0037971985bab9abfc0c72fc473d4eb839f2bb921000594cd4319c8cd4d5ee14c83fbb5d90b1928f61f2a11c1ef4a2b040bcbca8bca01d65efb989ebfc9bf733fdd377956a1eca525fa94050f9545546fd4a116b85e093f8c0d76185d6f89c7a4e0912abe6d5b16b9d4dd23289e6d8ddae40a9d327dc024131d85f1da2d6da9f0ed9018799d6db8b4389bfb077725e836c9c6828d1068183ad7da714323e845ea1cc742d334e70c46c34b8716a925f3c894a40fa1e4710b7d1ebac17fc5ca73f27d8bfee63d86640fe095bb169539ba198f850a63fe01727c5fd7d56ecabc17be5670f219c43107197c6f239f8245a895b83ca4021c1e6a104dc6a33184c52b5e26ee80ed6a937f11a72082c88a6605766a5a6d64834d69a3d337801b1a3e70cb9242f4b7307c3e37a7044610fa03a4135da567d", hex.EncodeToString(b.Witness.InvocationScript))
	assert.Equal(t, "552102486fd15702c4490a26703112a5cc1d0923fd697a33406bd5a1c00e0013b09a7021024c7b7fb6c310fccf1ba33b082519d82964ea93868d676662d4a59ad548df0e7d2102aaec38470f6aad0042c6e877cfd8087d2676b0f516fddd362801b9bd3936399e2103b209fd4f53a7170ea4444e0cb0a6bb6a53c2bd016926989cf85f9b0fba17a70c2103b8d9d5771d8f513aa0869b9cc8d50986403b78c6da36890638c3d46a5adce04a2102ca0e27697b9c248f6f16e085fd0061e26f44da85b58ee835c110caa5ec3ba5542102df48f60e8f3e01c48ff40b9b7f1310d7a8b2a193188befe1c2e3df740e89509357ae", hex.EncodeToString(b.Witness.VerificationScript))
	assert.Equal(t, "00000b94b3ff3e62c1f17c5291779173be7197e7626ebfaa545aeea50d99e6b5", b.Hash.ReverseString())

	bs, err := b.Size()
	assert.Equal(t, nil, err)
	assert.Equal(t, 2322, bs)

	buf := new(bytes.Buffer)

	b.Encode(buf)

	assert.Equal(t, rawBlock, hex.EncodeToString(buf.Bytes()))
}
```

**Comment by decentralisedkev** [comment]
My fault that this interface has grown so large. 

Let's trim it down by having it like this:

```
type Transacton interface {
Encode(io.Writer)
Decode(io.Reader)
Base() *Base
ID()
}
```

Then we can unexport the Hash field. *Base holds all of the fields that were deleted already, so we can further reduce by removing methods like Witness() that were exported for the interface

When testing the block code, we should not care about the specifics of each transaction, this can be put into a different test. All we care about is that the txHashes are correct and that all are present in the block.

**Comment by decentralisedkev** [comment]
One refactoring that we could do is; in the test case, define a slice of anonymous structs instead of the map. The order of the transactions in the block should stays the same, so we can just loop over the slice with it's index, and fail the test if it does not pass.

This way we can assert that the transactions are in the block and also that they are in the correct position.

**Comment by dauTT** [comment]
Actually, I will use the anonymout struct again and again for all my test cases. So wouldn't be better to define an unexport struct like this
```go
type txAttributes Struct{
			ID string 
			Type          string 
			Size          int 
			Version       int
			InputsLen     int
			OutputsLen    int
			AttributesLen int
			WitnessesLen  int
	}

func Testxxxx{
	expectedTxns:= []txAttributes{
		{----},
		{----},
	}

func Testyyyy{
	expectedTxns:= []txAttributes{
		{----},
		{----},
	}

}
```

**Comment by dauTT** [comment]
In regards to this improvement:

> My fault that this interface has grown so large.
> 
> Let's trim it down by having it like this:
> 
> ```
> type Transacton interface {
> Encode(io.Writer)
> Decode(io.Reader)
> Base() *Base
> ID()
> }
> ```

I think is a good idea. But the name `Base` can't be used because the specific transaction like the `MinerTransaction`:

```go
type Miner struct {
	*Base
	Nonce uint32
}
```
already used the `Base` name as a field and golang does not allow us to re-use the `Base` name to define the method:

```go
func(m  Miner) Base() *Base{
    return m.Base
}
```

So I will propose to use `BaseTx` as the function name and the interface will look as follow:

```go
type Transacton interface {
  Encode(io.Writer)
  Decode(io.Reader)
  BaseTx() *Base  
  ID()
  }
```

**OK?**

**Comment by decentralisedkev** [comment]
Yes I should have clarified, Encode and Decode still return an error. BaseTx sounds good.

I think only the Base struct needs the `BaseTx` method though? Since the others embed `*Base`

**Comment by decentralisedkev** [comment]
> ur expectation)

For the `size` not matching, we know now that it is because the c# implementation doesn't count the bytes for the gas field. So we would just need one or two test cases to check that we are consistent. 

I think when adding tests, they should be added to test a specific feature or functionality. Adding multiple tests that test the same thing would be a waste because if one fails, they all fail for the same reason. With the former approach it forces you to think about what and why you are testing something.

In that regard, I do not think we should have too many tests for the block decoding, as blocks do not differ by a large amount. We could possibly have another repo which runs a test on an offline chain to make sure everything is correct though

**Comment by decentralisedkev** [comment]
Since the hash is like a fingerprint for the block, for many things just checking that everything goes to the same hash correctly is fine, as hashing involves encoding all fields and using sha. Hope that makes sense. Feel free to call me out if you see me adding tests that look like they are doing the same thing!

**Comment by dauTT** [comment]
> For the `size` not matching, we know now that it is because the c# implementation doesn't count the bytes for the gas field. So we would just need one or two test cases to check that we are consistent.

Actually, Erik Fixed the issue in C#. So we don't have to add artificial logic to the size calculation. At least until we found the next bug. :smile: 


> n that regard, I do not think we should have too many tests for the block decoding, as blocks do not differ by a large amount. We could possibly have another repo which runs a test on an offline chain to make sure everything is correct though

Yes, I think that along with unit testing we should also have regression testing. both together will make the code very robust.

**Comment by decentralisedkev** [comment]
> Actually, Erik Fixed the issue in C#. So we don't have to add artificial logic to the size calculation. At least until we find the next bug. 

Great! I guess we can remove the `Size()` method since we have `Bytes()` already exposed, and `Size()` just adds an extra line of code to it. This would also make the interface smaller. WDYT?

**Comment by decentralisedkev** [comment]
I agree, regression testing is important. Let's put it on the back burner until all of the components are working and fully unit tested!

**Comment by dauTT** [comment]
> Great! I guess we can remove the `Size()` method since we have `Bytes()` already exposed, and `Size()` just adds an extra line of code to it. This would also make the interface smaller. WDYT?

I think you have good point. :+1:  

I have testd the size calculation looking at 1000 block test cases which have been automatically generated with neo-python: 

[block_test.go.txt](https://github.com/CityOfZion/neo-go/files/3000804/block_test.go.txt)

and your approach works worndefully. :smile: 

While testing the size calculation I discovered a bug inte transaction attrbiutes decoding/decoding. I will raise an issue for this and send a PR.

In regards to the size calculation task, I will refactor the `Transactioner interface` as we agree above and add only one block test. Is that ok?

**Comment by decentralisedkev** [comment]
SGTM!
