### ISSUE TITLE
Add Testify package

### ISSUE THREAD

**Issue by revett** [CityOfZion/neo-go#19]
Task to add the `assert` package for testing purposes.

https://github.com/stretchr/testify

**Comment by revett** [comment]
Will pick this up this weekend 👍

**Comment by anthdm** [comment]
@revett sweet

**Comment by anthdm** [comment]
@revett I introduced this package as from latest PR. I like the way we can use the assert functionality. However, overusing this package is something I won't recommend to do, it makes tests overly complicated, plain Go is easy to read for almost everyone. Closing this issue as resolved.
