### ISSUE TITLE
RPC: Implement missing API endpoints

### ISSUE THREAD

**Issue by anthdm** [CityOfZion/neo-go#4]
The basic setup for this is done. There's 1 method implemented (getconnectioncount). More could be implemented once the network and core package has more functionality.

**Comment by anthdm** [comment]
@stevenjack could you list up what is already implemented in neo-go for the RPC server? A checklist would be awesome. <3

**Comment by stevenjack** [comment]
@anthdm They're all in the README https://github.com/CityOfZion/neo-go/tree/master/pkg/rpc 👍

**Comment by hal0x2328** [comment]
Closing old issue in favor of rewrite suggested in #128
