### ISSUE TITLE
Using --out automatically appends .avm

### ISSUE THREAD

**Issue by jeroenptrs** [CityOfZion/neo-go#56]
If you use the --out arg when compiling, it will automatically append `.avm` to the file path you enter

For example:
`./bin/neo-go contract compile -i mycontract.go --out /Users/foo/bar/contract.avm`
will make a file called `contract.avm.avm` and
`./bin/neo-go contract compile -i mycontract.go --out /Users/foo/bar/contract`
will make a file called `contract.avm`

**Comment by anthdm** [comment]
Ty will fix this tomorrow in the morning
