### ISSUE TITLE
Compiler: optimize generated bytecode

### ISSUE THREAD

**Issue by anthdm** [CityOfZion/neo-go#65]
There are 3 main things that can be optimized:

### Removing nops right before function calls.
This can make contracts not compatible with other compilers that rely on that opcode.

### Removing the JMP 0x00 0x03 right before return statements.
This seems useless to me and van safe us 3 instructions before each return statement.

### replacing Ofromaltstack and Odup with Odupfromaltstack
We could save some significant space by optimizing this.

**Comment by anthdm** [comment]
If we merge the `neo-storm` compiler back in `neo-go` we get the optimized version for free.

**Comment by im-kulikov** [comment]
@anthdm hi there.. mb we can go another way (https://github.com/CityOfZion/neo-go/issues/110#issuecomment-444515401)?

By splitting repo into small parts we can make it more useful like libp2p or neo-python

---

Relates to https://github.com/CityOfZion/neo-go/issues/65#issuecomment-444822064 / https://github.com/CityOfZion/neo-go/issues/102#issuecomment-444821663

**Comment by hal0x2328** [comment]
Closing in favor of planned neo-storm integration
