### ISSUE TITLE
Compiler: Cannot compile multiple .go files in the same directory

### ISSUE THREAD

**Issue by anthdm** [CityOfZion/neo-go#76]
### Problem
Cannot compile .go files that are located in the same folder and therefore also share the same package name. This is a compiler build issue. Moving files to separate folder, thus also new package name will work fine.

**Comment by hal0x2328** [comment]
@anthdm Is this still unresolved?

**Comment by hal0x2328** [comment]
Assuming this will be fixed with the integration of the neo-storm compiler, closing.
