### ISSUE TITLE
Issues in signing data with the private key Sign function

### ISSUE THREAD

**Issue by ansrivas** [CityOfZion/neo-go#94]
I have been trying to sign a message both in golang and python. But they are coming out to be different.

Is there something which I am missing here ? Any hint would be great. I am attaching both the snippets here.

* This is the python example which works and I can use the signature for further usage.
```python

from neocore.Cryptography.Crypto import Crypto
msg = "010001f0907b22616d6f756e74223a22313030303030303030222c2261737365745f6964223a2253575448222c22626c6f636b636861696e223a226e656f222c22636f6e74726163745f68617368223a2261313935633135343965376461363162386461333135373635613739306163376537363333623832222c2274696d657374616d70223a313533343039333534333031327d0000"

pk = "d1c109c40976b1bf570e744e4d51df5224e3932b99dfd8bbdc2dac89fe4f6bd8"
print( Crypto.Sign(msg.encode(), pk).hex())
# final signature = "2be46cb14ebb4102f816f2e33489e2fa1a8d7ad8212a689efedfdb09aa621a725b926a426d8fe9575c5fb29eaef120da63a22b37d9c54e2e8662e96e23c42c4f"
```

* Here is the go-example for which I am using the `wallet` api: This signature is different from the python version ( I am not able to use it further as well )

```go
package main

import (
        "encoding/hex"
        "fmt"
        
        // Change this to neo-go wallet 
        "neo-go/wallet"

)

func main() {
        msg := []byte("010001f0907b22616d6f756e74223a22313030303030303030222c2261737365745f6964223a2253575448222c22626c6f636b636861696e223a226e656f222c22636f6e74726163745f68617368223a2261313935633135343965376461363162386461333135373635613739306163376537363333623832222c2274696d657374616d70223a313533343039333534333031327d0000")
        primaryKey := "d1c109c40976b1bf570e744e4d51df5224e3932b99dfd8bbdc2dac89fe4f6bd8"

        pk, err := wallet.NewPrivateKeyFromHex(primaryKey)
        if err != nil {
                panic(err)
        }
        signature, err := pk.Sign(msg)
        if err != nil {
                panic(err)
        }
        fmt.Println(hex.EncodeToString(signature))
}
// output is this following: 7c47632798b6377992027f5602d7681f6548c16cf060f835c3638dfb034e018f09269bbe6b68786d4afd7936f3244c1e894b8a24bcefa795c123a07449201a81
```

**Comment by ansrivas** [comment]
@anthdm any hint for this one? Still stuck here unfortunately.

**Comment by anthdm** [comment]
@ansrivas Will take a brief look into it today. Will keep you posted tonight, tomorrow at its latest. Is that fine for you?

**Comment by ansrivas** [comment]
Definitely no problem, thanks a lot.

**Comment by hal0x2328** [comment]
@ansrivas Were you able to resolve the problem?

**Comment by ansrivas** [comment]
@hal0x2328 no unfortunately, ended up using a different library.

**Comment by fyrchik** [comment]
@ansrivas One problem is the way you convert message to bytes. With `[]byte(...)` you are just getting string representation as a sequence of character codes.
Try to use `msg, err := hex.DecodeString(...)`, then you get a result first half of which is equal to neo-python's. :)
