### ISSUE TITLE
Encrypt privkey bug in wallet.NEP2Encrypt?

### ISSUE THREAD

**Issue by henly2** [CityOfZion/neo-go#95]
When call wallet.NEP2Decrypt(key, passphrase string), return "password mismatch";  
Is the reason:
encrypted, err := crypto.AESEncrypt(derivedKey2, xr) -> encrypted, err := crypto.AESEncrypt(xr, derivedKey2); because xr is the source, derivedKey2 is key?
Sorry for poor English.

**Comment by anthdm** [comment]
Hmm interesting, I will take a look into it. Thanks, @henly2 for the bug report.

**Comment by im-kulikov** [comment]
@anthdm https://github.com/CityOfZion/neo-go/pull/108 close this issue?
